### ISSUE TITLE
Error printing out the link when it was an image

### ISSUE THREAD

**Issue by ExtraExaByte** [nakulnandhakumar/markdown-parse#1]
A mark down file that has a link such as the following:
```
![image](something.com)
```
would print out 
```
[something.com]
``` 

when it should have not printed anything given that the provided file contains an image and not a link.

A recommended fix for the issue is to create an if statement within the while loop, checking if the character before the open bracket is an exclamation mark.  If it is an exclamation mark, then the program should not print that link.

**Comment by nakulnandhakumar** [comment]
Resolved
